// frameworks/qwik/app.tsx
import '@builder.io/qwik/qwikloader.js'
import { render } from '@builder.io/qwik'
import { component$, useSignal } from '@builder.io/qwik'
import '../../packages/u-progress'
import '../../packages/u-datalist'
import '../../packages/u-tags'

const App = component$(() => {
  const count = useSignal(0)
  const value = useSignal('')

  return (
    <div>
      <h1>Qwik + u-elements</h1>
      <button onClick$={() => count.value++}>count is {count.value}</button>
      <u-progress value="15" max="20"></u-progress>
      <br />
      <br />
      {/* @ts-ignore */}
      <input list="my-list" value={value.value} onInput$={() => (value.value = '-') && (value.value = '')} />
      <u-datalist id="my-list" data-singular="%d hit" data-plural="%d hits">
        <u-option value="test-1">Test 1</u-option>
        <u-option value="test-2">Test 2</u-option>
        <u-option value="test-3">Test 3</u-option>
      </u-datalist>
      <u-tags class="my-class" onTags$={console.log}>
        <data>Kokkos</data>
        <data>Banan</data>
        <data>Jordbær</data>
        <input type="text" />
      </u-tags>
    </div>
  )
})

render(document.getElementById('app') as HTMLElement, <App />)

// frameworks/preact/app.tsx
import { useRef, useState } from 'preact/hooks'
import { render } from 'preact'
import type { UHTMLTagsElement } from '../../packages/u-tags'
import '../../packages/u-progress'
import '../../packages/u-datalist'
import '../../packages/u-tags'

export default function App() {
  const [count, setCount] = useState(0)
  const [value, setValue] = useState('')
  const ref = useRef<UHTMLTagsElement>(null);

  return (
    <div>
      <h1>Preact + u-elements</h1>
      <button onClick={() => setCount((count) => count + 1)}>
        count is {count}
      </button>
      <u-progress value="5" max="15"></u-progress>
      <br />
      <br />
      <label htmlFor="my-input"></label>
      <input id="my-input" list="my-list" value={value} onChange={() => setValue('')} />
      <u-datalist id="my-list" class="my-class-name" data-singular="%d hit" data-plural="%d hits">
        <u-option value="test-1">Test 1</u-option>
        <u-option value="test-2">Test 2</u-option>
        <u-option value="test-3">Test 3</u-option>
      </u-datalist>
      <u-tags ref={ref} ontags={console.log}>
        <data>Kokkos</data>
        <data>Banan</data>
        <data>Jordbær</data>
        <input type="text" />
      </u-tags>
    </div>
  )
}

render(<App />, document.getElementById('root')!)
