// frameworks/vue/test.u-combobox.vue
<script setup lang="ts">
// Vue harness page for the shared u-combobox suite (packages/u-combobox/u-combobox.suite.ts).
// Items are rendered from reactive state (controlled), the input uses v-model,
// and all combobox events are bound with Vue event listeners.
import { nextTick, reactive } from "vue";
import "../../packages/u-datalist/u-datalist";
import "../../packages/u-combobox/u-combobox";
import {
	comboboxAttrs,
	createHarness,
	type HarnessConfig,
	handleBeforeSelect,
	handleInput,
	handleSubmit,
	listId,
	log,
	optionAttrs,
	optionKey,
	optionTag,
} from "../../packages/u-combobox/u-combobox.harness";

const state = reactive<{ cfgs: HarnessConfig[] }>({ cfgs: [] });

createHarness({
	render: async (cfgs) => {
		state.cfgs = cfgs;
		await nextTick();
	},
	update: async (patch, index) => {
		Object.assign(state.cfgs[index], patch);
		await nextTick();
	},
});

const inputAttrs = (cfg: HarnessConfig) => ({
	type: cfg.inputAttrs.type,
	readonly: cfg.inputAttrs.readonly !== undefined,
	disabled: cfg.inputAttrs.disabled !== undefined,
	form: cfg.form === "outside" ? "form" : undefined,
});
</script>

<template>
  <template v-for="(cfg, index) in state.cfgs" :key="index">
    <template v-if="cfg.mounted">
      <label v-if="cfg.label" :for="cfg.id">Label</label>
      <form v-if="cfg.form === 'outside'" id="form" @submit="handleSubmit">
        <input id="other" name="other" value="keep" />
        <button type="submit">Send</button>
      </form>
      <component
        :is="cfg.form === true ? 'form' : 'div'"
        :id="cfg.form === true ? 'form' : undefined"
        @submit="handleSubmit"
      >
        <u-combobox
          v-bind="comboboxAttrs(cfg)"
          @comboboxbeforeselect="handleBeforeSelect($event, cfg, (items) => (cfg.items = items))"
          @comboboxafterselect="log('comboboxafterselect', $event)"
          @comboboxbeforematch="log('comboboxbeforematch', $event)"
          @input="handleInput($event, cfg, (options) => (cfg.options = options))"
          @change="log('change', $event)"
        >
          <select v-if="cfg.select" :name="cfg.select" hidden></select>
          <data v-for="item in cfg.items" :key="item.value" :value="item.value">{{ item.label }}</data>
          <input :id="cfg.id" :list="listId(cfg)" v-model="cfg.value" v-bind="inputAttrs(cfg)" />
          <button v-if="cfg.toggle" type="button" aria-expanded="false">Toggle</button>
          <del v-if="cfg.clear === 'del'"></del>
          <button v-else-if="cfg.clear" type="reset">Clear</button>
          <component
            v-if="cfg.options"
            :is="cfg.listTag"
            :key="cfg.listKey"
            :id="listId(cfg)"
            :data-nofilter="cfg.nofilter ? '' : null"
          >
            <component
              v-for="option in cfg.options"
              :is="optionTag(cfg)"
              :key="optionKey(option)"
              v-bind="optionAttrs(option)"
            >{{ option.text }}</component>
          </component>
        </u-combobox>
        <template v-if="cfg.form === true">
          <input id="other" name="other" value="keep" />
          <button type="submit">Send</button>
        </template>
      </component>
    </template>
  </template>
</template>

// frameworks/svelte/test.u-combobox.svelte
<script lang="ts">
// Svelte harness page for the shared u-combobox suite (packages/u-combobox/u-combobox.suite.ts).
// Items are rendered from $state (controlled), the input uses bind:value,
// and all combobox events are bound with Svelte event attributes.
import { flushSync } from "svelte";
import "../../packages/u-datalist/u-datalist";
import "../../packages/u-combobox/u-combobox";
import {
	comboboxAttrs,
	createHarness,
	type HarnessConfig,
	handleBeforeSelect,
	handleInput,
	handleSubmit,
	listId,
	log,
	optionAttrs,
	optionKey,
	optionTag,
} from "../../packages/u-combobox/u-combobox.harness";

let cfgs = $state<HarnessConfig[]>([]);

createHarness({
	render: (next) => {
		cfgs = next;
		flushSync();
	},
	update: (patch, index) => {
		Object.assign(cfgs[index], patch);
		flushSync();
	},
});
</script>

{#each cfgs as cfg, index (index)}
	{#if cfg.mounted}
		{#if cfg.label}<label for={cfg.id}>Label</label>{/if}
		{#if cfg.form === "outside"}
			<form id="form" onsubmit={handleSubmit}>
				<input id="other" name="other" value="keep" />
				<button type="submit">Send</button>
			</form>
		{/if}
		<svelte:element
			this={cfg.form === true ? "form" : "div"}
			id={cfg.form === true ? "form" : undefined}
			onsubmit={handleSubmit}
		>
			<u-combobox
				{...comboboxAttrs(cfg)}
				oncomboboxbeforeselect={(event: Event) => handleBeforeSelect(event, cfg, (items) => (cfg.items = items))}
				oncomboboxafterselect={(event: Event) => log("comboboxafterselect", event)}
				oncomboboxbeforematch={(event: Event) => log("comboboxbeforematch", event)}
				oninput={(event: Event) => handleInput(event, cfg, (options) => (cfg.options = options))}
				onchange={(event: Event) => log("change", event)}
			>
				{#if cfg.select}<select name={cfg.select} hidden></select>{/if}
				{#each cfg.items as item (item.value)}
					<data value={item.value}>{item.label}</data>
				{/each}
				<!-- bind:value requires a static type, so email is a separate input -->
				{#if cfg.inputAttrs.type === "email"}
					<input
						type="email"
						id={cfg.id}
						list={listId(cfg)}
						form={cfg.form === "outside" ? "form" : undefined}
						readonly={cfg.inputAttrs.readonly !== undefined}
						disabled={cfg.inputAttrs.disabled !== undefined}
						bind:value={cfg.value}
					/>
				{:else}
					<input
						type="text"
						id={cfg.id}
						list={listId(cfg)}
						form={cfg.form === "outside" ? "form" : undefined}
						readonly={cfg.inputAttrs.readonly !== undefined}
						disabled={cfg.inputAttrs.disabled !== undefined}
						bind:value={cfg.value}
					/>
				{/if}
				{#if cfg.toggle}<button type="button" aria-expanded="false">Toggle</button>{/if}
				{#if cfg.clear === "del"}<del></del>{:else if cfg.clear}<button type="reset">Clear</button>{/if}
				{#if cfg.options}
					{#key cfg.listKey}
						<svelte:element
							this={cfg.listTag}
							id={listId(cfg)}
							data-nofilter={cfg.nofilter ? "" : undefined}
						>
							{#each cfg.options as option (optionKey(option))}
								<svelte:element this={optionTag(cfg)} {...optionAttrs(option)}>{option.text}</svelte:element>
							{/each}
						</svelte:element>
					{/key}
				{/if}
			</u-combobox>
			{#if cfg.form === true}
				<input id="other" name="other" value="keep" />
				<button type="submit">Send</button>
			{/if}
		</svelte:element>
	{/if}
{/each}
